# ownCloud with MariaDB/MySQL
#
# Access via "http://localhost:8080" (or "http://$(docker-machine ip):8080" if using docker-machine)
#
# During initial ownCloud setup, select "Storage & database" --> "Configure the database" --> "MySQL/MariaDB" Database user: root Database password: example Database name: pick any name 
# Database host: replace "localhost" with "mysql"
version: '2' 
services:
  owncloud:
    image: owncloud:9.1
    ports:
      - 8080:80
    volumes:
      - /root/Owncloud:/var/www/owncloud/data
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: Owncloud1994
