FROM ruby:2.3.3
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs
RUN mkdir /WebsiteApp
WORKDIR /WebsiteApp
ADD Gemfile /WebsiteApp/Gemfile
ADD Gemfile.lock /WebsiteApp/Gemfile.lock
RUN bundle install
ADD . /WebsiteApp
EXPOSE 80
